#!/usr/bin/env perl
# This program checks if certain files that are to be commited
# are generated by a program from the autotools suite; if this is
# the case, the commit is refused
$directory = $ARGV[0]; # The directory-name is only informational, all
                       # files we need to check will be in our CWD
$error = 0;
$FILEPATTERN = "^(Makefile.*|config.*)"; # all files matching this pattern will be checked

$SEARCHPATTERN = "generated.*by (configure|automake|autoheader)"; # If the file contains this string, 
                                                                  # it should be considered generated by autotools
$FIRSTNLINES = 10; # Check the first ten lines for SEARCHPATTERN

shift; # skip directory name

while ($#ARGV >= 0) {
    $file = $ARGV[0];
    if ($file =~ /$FILEPATTERN/) {
	$lines = 0;
	open FILE,$file;
	while (<FILE>) {
	    if (/$SEARCHPATTERN/i) {
		print "ERROR! $directory/$file is generated by autotools, it must not be commited!\n";
		$error = 1;
	       last;
	    }
	    $lines++;
	    last if ($lines>$FIRSTNLINES);
	}
    }
    shift;
}
close FILE;
exit $error;

